import type { Item, Fields, Kind, Member, Activity } from "./model";
const stamp = "2026-10-03T09:00:00Z";
const make = (
  id: string,
  kind: Kind,
  title: string,
  parent_id: string | null,
  fields: Fields = {},
  related_id: string | null = null,
): Item => ({
  id,
  kind,
  title,
  parent_id,
  fields,
  related_id,
  workspace_id: "demo",
  owner_id: "demo-user",
  created_by: "demo-user",
  updated_by: "demo-user",
  created_at: stamp,
  updated_at: stamp,
});
export const demoMembers: Member[] = [
  { user_id: "demo-user", name: "Responsable de ejemplo", role: "owner" },
  { user_id: "demo-growth", name: "Equipo Growth · ejemplo", role: "editor" },
];
export const demoItems: Item[] = [
  make("nsm", "north_star", "Objetos recuperados por semana", null, {
    metric: "Recuperaciones confirmadas",
    definition:
      "Un objeto publicado cuya recogida ha sido confirmada por la persona que lo recupera. Sin duplicados ni cancelaciones.",
    frequency: "Semanal",
    value_moment: "Una persona recoge y vuelve a utilizar un objeto.",
    baseline: 100,
    current: 142,
    target: 200,
    unit: "objetos",
    source: "Confirmaciones de recogida · ejemplo",
  }),
  make("g1", "goal", "Aumentar las publicaciones útiles", "nsm", {
    metric: "Publicaciones válidas / semana",
    baseline: 200,
    current: 265,
    target: 400,
    unit: "publicaciones",
    stage: "Activación",
  }),
  make("g2", "goal", "Facilitar que los objetos se recuperen", "nsm", {
    metric: "Tasa de recuperación",
    baseline: 25,
    current: 31,
    target: 40,
    unit: "%",
    stage: "Retención",
  }),
  make(
    "o1",
    "opportunity",
    "El valor de publicar no se entiende al entrar",
    "g1",
    {
      evidence:
        "Ejemplo: en entrevistas, los usuarios no identifican el beneficio de compartir un hallazgo.",
      source: "Entrevistas de ejemplo",
      opportunity_type: "Problema",
      focus: true,
      stage: "Activación",
    },
  ),
  make(
    "o2",
    "opportunity",
    "Los antiguos usuarios no vuelven a publicar",
    "g1",
    {
      evidence: "Ejemplo: la segunda publicación es poco frecuente.",
      source: "Cohorte de ejemplo",
      opportunity_type: "Oportunidad",
      focus: true,
      stage: "Retención",
    },
  ),
  make(
    "o3",
    "opportunity",
    "La incertidumbre sobre el estado frena la recogida",
    "g2",
    {
      evidence: "Ejemplo: usuarios preguntan si el objeto sigue disponible.",
      source: "Conversaciones de ejemplo",
      opportunity_type: "Problema",
      stage: "Activación",
    },
  ),
  make("i1", "idea", "Explicar el beneficio antes del formulario", "o1", {
    impact: 8,
    confidence: 7,
    ease: 9,
    description:
      "Dar una razón concreta para publicar y reducir la incertidumbre.",
  }),
  make("i2", "idea", "Recordatorio con objetos cercanos", "o2", {
    impact: 7,
    confidence: 6,
    ease: 8,
    description: "Probar un mensaje de reactivación contextual.",
  }),
  make("i3", "idea", "Confirmación de disponibilidad reciente", "o3", {
    impact: 9,
    confidence: 5,
    ease: 5,
    description: "Mostrar cuándo se comprobó que el objeto sigue allí.",
  }),
  make("ob1", "objective", "Hacer de la recuperación un hábito", null, {
    period: "2026-Q4",
    description:
      "Aportar valor recurrente a quienes publican y recogen objetos.",
  }),
  make(
    "kr1",
    "kr",
    "Llegar a 400 publicaciones válidas semanales",
    "ob1",
    {
      metric: "Publicaciones válidas / semana",
      baseline: 200,
      current: 265,
      target: 400,
      unit: "publicaciones",
      period: "2026-Q4",
    },
    "g1",
  ),
  make(
    "kr2",
    "kr",
    "Elevar la recuperación del 25% al 40%",
    "ob1",
    {
      metric: "Tasa de recuperación",
      baseline: 25,
      current: 31,
      target: 40,
      unit: "%",
      period: "2026-Q4",
    },
    "g2",
  ),
  make(
    "p1",
    "project",
    "Activación de nuevos publicadores",
    null,
    {
      description:
        "Coordinar producto y adquisición para mejorar la primera publicación.",
      status: "En curso",
      start: "2026-10-01",
      end: "2026-12-15",
    },
    "g1",
  ),
  make("e1", "experiment", "Un beneficio claro antes de publicar", "i1", {
    status: "En curso",
    channel: "Producto / Web",
    method: "A/B aleatorizado",
    hypothesis:
      "Si explicamos el beneficio de publicar antes del formulario, aumentará la proporción de personas que completan una publicación.",
    metric: "Publicación completada / usuario expuesto",
    baseline: 18,
    target: 22,
    unit: "%",
    success_criteria:
      "Mejora relativa de al menos 20%, sin empeorar la calidad de las publicaciones.",
    guardrail: "Porcentaje de publicaciones inválidas",
    control: "Mensaje actual",
    variant: "Explicación del beneficio + CTA",
    sample_target: 2000,
    start: "2026-10-01",
    end: "2026-10-21",
    cost: 0,
    impact: 8,
    confidence: 7,
    ease: 9,
    project_id: "p1",
    kr_ids: "kr1",
    control_n: 340,
    control_success: 61,
    variant_n: 338,
    variant_success: 72,
    source_url: "",
    external_id: "publish-value-cta",
  }),
  make("e2", "experiment", "Email de reactivación con contexto local", "i2", {
    status: "Diseñado",
    channel: "Email",
    method: "A/B aleatorizado",
    hypothesis:
      "Si el email muestra objetos cercanos, más usuarios volverán a publicar esa semana.",
    metric: "Usuarios que publican / emails entregados",
    baseline: 4,
    target: 6,
    unit: "%",
    success_criteria:
      "Alcanzar 6% sin elevar la tasa de bajas por encima de 0,5%.",
    guardrail: "Bajas de suscripción",
    start: "2026-10-12",
    end: "2026-10-26",
    cost: 40,
    impact: 7,
    confidence: 6,
    ease: 8,
    kr_ids: "kr1",
  }),
  make("e3", "experiment", "Anuncio centrado en el valor del hallazgo", "i1", {
    status: "Finalizado",
    channel: "Meta Ads",
    method: "A/B aleatorizado",
    hypothesis:
      "Mostrar el impacto de recuperar objetos aumentará la activación de los nuevos usuarios.",
    metric: "Coste por usuario que publica",
    baseline: 8,
    target: 6,
    unit: "USD",
    success_criteria: "Coste inferior a 6 USD por usuario activado.",
    start: "2026-09-10",
    end: "2026-09-24",
    cost: 180,
    result: "El coste de la variante fue 6,8 USD. No alcanzó el objetivo.",
    conclusion: "No se cumplió el criterio de éxito.",
    learning:
      "El mensaje atrae clics, pero no mejora suficientemente la primera publicación.",
    decision: "Iterar",
    impact: 6,
    confidence: 5,
    ease: 8,
    kr_ids: "kr1",
  }),
];
for (const e of demoItems.filter((i) => i.kind === "experiment")) {
  e.fields.e_id = "EXP-" + e.id.toUpperCase();
  e.fields.variants = JSON.stringify([
    {
      name: "A · Control",
      description: String(e.fields.control || "Situación actual"),
      traffic: 50,
      exposed: Number(e.fields.control_n || 0),
      conversions: Number(e.fields.control_success || 0),
      result: "",
      success: "",
    },
    {
      name: "B",
      description: String(e.fields.variant || "Cambio propuesto"),
      traffic: 50,
      exposed: Number(e.fields.variant_n || 0),
      conversions: Number(e.fields.variant_success || 0),
      result: "",
      success: "",
    },
  ]);
}
export const demoActivity: Activity[] = [
  {
    id: "a1",
    actor_id: "demo-user",
    action: "update",
    record_id: "e1",
    title: "Un beneficio claro antes de publicar",
    created_at: stamp,
  },
  {
    id: "a2",
    actor_id: "demo-growth",
    action: "insert",
    record_id: "e2",
    title: "Email de reactivación con contexto local",
    created_at: stamp,
  },
];
